apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: custom-index-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: custom-index-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 4444  # Your desire port number
      targetPort: 80
  externalIPs:   # Add this section to specify external IP
    - 192.168.1.100   # Replace <external_ip> with the actual external IP address
